### ISSUE TITLE
Add a Code of Conduct?

### ISSUE THREAD

**Issue by rory** [EqualStreetNames/equalstreetnames#14]
Hi all. Many projects now-a-days have a Code of Conduct. It's good to write that down before anything happens, when a project, like this, is young. There isn't one written down yet. So I suggest one be added? What do yous (the admins) think?

I suggest the [diversity-talk OSM mailing list CoC](https://wiki.openstreetmap.org/wiki/Diversity/MailingList/CodeOfConduct).

**Comment by jbelien** [comment]
Hello @rory ,

It's indeed a good idea to add a Code of Conduct !
Thanks for the suggested CoC, I'll forward it to the person coordinating the project!
