### ISSUE TITLE
New Feature: Count tagged in osm, tagged in config.php, untagged

### ISSUE THREAD

**Issue by ynux** [EqualStreetNames/equalstreetnames#146]
To see the progress as we work our way through the city map, it would be great to see:
  *   For how many streets there was a tag name:etymology:wikidata found in OpenStreetMap
  *   For how many streets there was a tag found in the config.php
  *   For how many streets nothing was found
So far, all streets that are untagged or tagged with an entity without gender are white. 
It could also make sense to have a new color, e.g. gray, for untagged streets.

**Comment by RobinLinde** [comment]
Would be great to see also streets that don't have anything in `statistics.json`. That would definitely help me with the [statistics](https://github.com/RobinLinde/statistics) project I'm currently breaking my head over.

**Comment by jbelien** [comment]
@ynux Update has been made for Munich !

You'll find the statistics in [`sources.json`](https://github.com/EqualStreetNames/equalstreetnames-munich/blob/master/data/sources.json) and a "source" column has been added to the CSV files (see [`gender.csv`](https://github.com/EqualStreetNames/equalstreetnames-munich/blob/master/data/gender.csv))

**Comment by RobinLinde** [comment]
Also added `sources.json` to [statistics.equalstreetnames.eu](https://statistics.equalstreetnames.eu/), not completely sure about the visualisation yet.
