### ISSUE TITLE
php memory exhausted

### ISSUE THREAD

**Issue by ynux** [EqualStreetNames/equalstreetnames#147]
When running my `php composer.phar run update-data -- --city=munich` with the full beauty of Munich, that is

```
[out:json][timeout:300];
( area["wikidata"="Q1726"]; )->.a;
(
	way["highway"]["name"]["highway"!="bus_stop"]["highway"!="proposed"]["highway"!="service"]["highway"!="platform"](area.a);
	way["place"="square"]["name"](area.a);
);
out body;
>;
out skel qt;
```
I get an error

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 45056 bytes) in /Users/xxx/gitrepos/equalstreetnames/scripts/library/geojson/wikidata.php on line 28
Script php scripts/geojson.php handling the geojson event returned with error code 255
Script @geojson was called via update-data
`

Disclaimer: I did not try to resolve this by giving more memory to php, or running it on a stronger machine (my MacBook has 8GB of memory). I just reduced Munich to the part of the city where I live and hope for someone else to solve this ;-)

**Comment by RobinLinde** [comment]
For me, setting `memory_limit` in php.ini to `1024M` was enough to be able to update data for Munich. Probably a good idea to at least mention it somewhere like the [replicate.md](https://github.com/openknowledgebe/equalstreetnames/blob/master/docs/replicate.md), or the [scripts readme](https://github.com/openknowledgebe/equalstreetnames/blob/master/docs/scripts/README.md).

**Comment by jbelien** [comment]
Thanks @RobinLinde, good to know.
I'll try to figure out how to improve the process so it's not necessary to increase PHP memory (the idea is to make the process work for any city, including Beijing for instance :P)

**Comment by jbelien** [comment]
Data process has been completely refactored.
That should improve performances.
I'll reopen this issue if needed.
