### ISSUE TITLE
Regrouping all cities in one GitHub organization

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#148]
First things first: I am more than happy and proud to see more and more cities replicating our EqualStreetNames project.

Since more and more cities are joining the party and each city has its own repository, it starts to be "a lot" of repository just to run this project.
For Belgium only, including this repository, we now have 9 repositories than I'm managing.

This last month people have contacted me to help them replicate the project in their city ; I first thought about asking them to take care of the repository because it doesn't make much sense to have a repository for a city in Germany (for instance) under Open Knowledge Belgium organization.

Since the process is fully automated (data update + website deployment), it doesn't cost much to add ANY city to the project, we just need the data to be available.

So, my idea is : Migrate ALL repositories to one single "EqualStreetNames" GitHub organization.
I see 2 main advantages to that new structure:
- If people what to add their city to the project, they could just open an issue and I would just have to create a new repository for that city in the "EqualStreetNames" organization
- For now, people can't update the sub-modules without sending a Pull Request, having everything under the same organization would allow all the people that are maintaining the data repositories to update the main repository after each data update (like I currently do for Belgium) ; they wouldn't have to fork the main repository anymore

The main project would still stay under Open Knowledge Belgium umbrella (I am one of the board member) and each "city maintainer" would of course stay "owner" of their repository if they want to but would also become member of the "EqualStreetNames" GitHub organization.

@stalker314314 @robinlinde @gislars @ynux @mitmirzutun I would like to know what you think about this idea. Feel free to challenge it !

**Comment by RobinLinde** [comment]
At first sight it seems like a very good idea, would also fix the issues I was having (https://github.com/openknowledgebe/equalstreetnames/pull/143). Might also open up possibilities for creating teams. Will try to post some more when I get back from IKEA.

**Comment by stalker314314** [comment]
I would not even mind if this would be centrally managed repo (with all cities in same repo, one website...), and I certainly don't mind if this is all under one GitHub org. Go for it and let me know once you create it, so I can migrate!

**Comment by RobinLinde** [comment]
Back from IKEA (no better way to spend a birthday 😛) now (and done with fixing some Docker containers), I guess this would also allow more easy collaboration and discussion for cities/regions/countries in corresponding teams. Will be interesting to see how everything works out. Also hope to do something like a single website and frontend later this year...

**Comment by jbelien** [comment]
Happy birthday @RobinLinde 🎁

I'll create the new organization tomorrow 👍

**Comment by iLienstAr** [comment]
@jbelien this is the way to go! I like the idea, also community wise: it becomes an international, let's get rid of the borders at EqualStreetNames ;)

**Comment by stalker314314** [comment]
Hi, I forked Belgrade to EqualStreetNames. If I should transfer instead, let me know!

**Comment by jbelien** [comment]
> Hi, I forked Belgrade to EqualStreetNames. If I should transfer instead, let me know!

@stalker314314 Indeed, I was more thinking of a transfer than a fork but that's really up to you :)

**Comment by stalker314314** [comment]
No problem, done now!

**Comment by jbelien** [comment]
> No problem, done now!

@stalker314314 Awesome ! I'm updating the submodules reference ! 👍

**Comment by RobinLinde** [comment]
Transfered [equalstreetnames-groningen](https://github.com/EqualStreetNames/equalstreetnames-groningen) and [equalstreetnames-assen](https://github.com/EqualStreetNames/equalstreetnames-assen). Just need to remove/update Github Actions.

**Comment by jbelien** [comment]
I've consolidated all the repositories already transferred including automated updates (sub-module + main repository).

@RobinLinde Push to main repository failed ([Assen](https://github.com/EqualStreetNames/equalstreetnames-assen/runs/2160194414?check_suite_focus=true#step:12:7) & [Groningen](https://github.com/EqualStreetNames/equalstreetnames-groningen/runs/2160199043?check_suite_focus=true#step:12:7)) because it used your `ACCESS_TOKEN`. I removed it so it uses the `ACCESS_TOKEN` from the organization so it should work fine during the next run.

**Comment by jbelien** [comment]
I didn't update the deployment workflow yet.

**Comment by gislars** [comment]
I just transfered "berlin" to this new orga. Thanks @jbelien for consolidating.

**Comment by RobinLinde** [comment]
> 
> 
> I didn't update the deployment workflows yet.

@jbelien I believe i have a working deployment workflow in [deploy.yml](https://github.com/EqualStreetNames/equalstreetnames-assen/blob/master/.github/workflows/deploy.yml) over at `equalstreetnames-assen`. Feel free to take a look and point out anything i've missed, getting a bit 😴.

**Comment by jbelien** [comment]
Awesome, great job @RobinLinde !
I didn't know about the `on.workflow_run`, this is perfect for our use case !

I updated my `deploy.yml` files for Belgium (see [`deploy.yml` for Brugge](https://github.com/EqualStreetNames/equalstreetnames-brugge/blob/master/.github/workflows/deploy.yml), for instance)

**Comment by jbelien** [comment]
To help people replicating the project in their city, I have added a "template repository" : https://github.com/EqualStreetNames/equalstreetnames-template

Feedback is more than welcome :)

**Comment by ynux** [comment]
That is perfect. I was looking for a place to put our learnings. I forked it.

**Comment by RobinLinde** [comment]
> 
> 
> To help people replicating the project in their city, I have added a "template repository" : https://github.com/EqualStreetNames/equalstreetnames-template
> 
> Feedback is more than welcome :)

@jbelien Looks good, but it might be useful to mention that it needs to be included in the package.json, something like [this](https://github.com/RobinLinde/equalstreetnames-template/commit/b884f78084e969ca29d5f36d00ab7b8d2476dc73). If you want I can open a PR.

I'm also trying to improve some of the other documentation, lint them with markdownlint and adding a guide how to get started and set up an environment over in my [`docs`](https://github.com/RobinLinde/equalstreetnames/tree/docs) branch. I think files like `docs/municipalities.md` might be moved to `equalstreetnames-brussels`

As always, feedback or any other comments are always welcome ;)

**Comment by jbelien** [comment]
> [...]  it might be useful to mention that it needs to be included in the package.json, something like this. If you want I can open a PR.

You're absolutely right, I forgot that step.
I'll add it. 👍 

> I'm also trying to improve some of the other documentation [...]

Update of the documentation is indeed long overdue (see #27).
I'll make a first "cleaning" tonight.

**Comment by RobinLinde** [comment]
While going through all the documentation I noticed `app.countries` might also need to be set to the correct country.

**Comment by jbelien** [comment]
> While going through all the documentation I noticed app.countries might also need to be set to the correct country.

Oh, indeed ! Good catch ! 👍

**Comment by RobinLinde** [comment]
Opened a pull request for now: https://github.com/EqualStreetNames/equalstreetnames/pull/152, feel free to give feedback and/or comments.

**Comment by ynux** [comment]
Would be helpful to add version information for the software used, like  
* git version minimum 1.5.3 (to handle submodules), 
* node ( v8.2.1 does not work , v14.16.0 works)  
* php (7.3.11 works)
Does not have to be perfect, just known-to-work versions.

**Comment by jbelien** [comment]
> Would be helpful to add version information for the software used, like [...]

To be honest, it doesn't really matter, you just need a "recent" version.

**Comment by jbelien** [comment]
@RobinLinde I have merged your documentation update, thanks a lot !

I have restructured it a bit.
I'll update the scripts documentation and the replication documentation later today or tomorrow.

**Comment by jbelien** [comment]
Thanks a lot for all your feedback !
I still need to finish some documentation but I think the restructuring is complete and the replication process is easier than ever.
