### ISSUE TITLE
Include config.php gender data in statistics

### ISSUE THREAD

**Issue by ynux** [EqualStreetNames/equalstreetnames#151]
Only applicable if they aren't included yet, but I don't think they are, from looking at the code and the data. For our part of Munich I can see that nearly all streets are named after persons, but the statistics claim it's only half.

Also, add a caveat in the text that these statistics aren't complete due to incomplete information.

A claim such as for Munich "Out of 6683 streetnames, 78 (1.17%) are based on a person. " is incorrect.

**Comment by jbelien** [comment]
> Only applicable if they aren't included yet, but I don't think they are, from looking at the code and the data. For our part of Munich I can see that nearly all streets are named after persons, but the statistics claim it's only half.

All the ways/relations defined in [`$config['gender']` in `config.php`](https://github.com/EqualStreetNames/equalstreetnames-template/blob/master/config.php#L15-L18) are included in the statistics (see [`geojson.php (line 72)`](https://github.com/EqualStreetNames/equalstreetnames/blob/master/scripts/geojson.php#L72) + [`geojson.php (line 138)`](https://github.com/EqualStreetNames/equalstreetnames/blob/master/scripts/geojson.php#L138)) !

> Also, add a caveat in the text that these statistics aren't complete due to incomplete information.
> 
> A claim such as for Munich "Out of 6683 streetnames, 78 (1.17%) are based on a person. " is incorrect.

The text is currently "Out of 3018 streetnames, 632 (20.94%) **have been found to be named** after a person. ".
That update has been made (for all the city in Belgium) in October 2020 (see #97).
You probably forked Munich from a city that didn't do that update.

**Comment by RobinLinde** [comment]
I've just done the update for Assen and Groningen (which Munich seems to be based one), missed out on that.
