### ISSUE TITLE
New Repository for city Halle(Saale) in Germany

### ISSUE THREAD

**Issue by hjoertel** [EqualStreetNames/equalstreetnames#163]

**Comment by jbelien** [comment]
Awesome ! 👍 

I guess this is the repository : https://github.com/hjoertel/equalstreetnames
I'll create a new team for Saale, Germany so you'll be able to transfer the repository to this organization (or do you prefer not to transfer it ?).

**Comment by hjoertel** [comment]
Am Donnerstag, 8. April 2021, 14:38:46 CEST schrieb Jonathan Beliën:
> 
> Awesome ! 👍

I'm glad that I could do it, thanks

> 
> I guess this is the repository : https://github.com/hjoertel/equalstreetnames

Yes

> I'll create a new team for Saale, Germany

The city is Halle, but because we have some cities with this name, it is officially called 
    Halle(Saale)

means Halle on the river Saale.



> so you'll be able to transfer the repository to this organization (or do you prefer not to transfer it ?).

Of course, I like to have it trensferred.

Greetings
	Heinz

**Comment by jbelien** [comment]
> Of course, I like to have it trensferred.

You just need to accept the invitation to the [team](https://github.com/orgs/EqualStreetNames/teams/halle-saale) I've sent you.

Once it's done, you can transfer your repository to `EqualStreetNames` organization (in your repository settings).
You will have to rename it `equalstreetnames-halle-saale`.

**Comment by hjoertel** [comment]
Am Donnerstag, 8. April 2021, 15:20:47 CEST schrieb Jonathan Beliën:
> > Of course, I like to have it trensferred.
> 
> You just need to accept the invitation to the [team](https://github.com/orgs/EqualStreetNames/teams/halle-saale) I've sent you.
> 
> Once it's done, you can transfer your repository to `EqualStreetNames` organization (in your repository settings).
> You will have to rename it `equalstreetnames-halle-saale`.
> 
Done,

	Heinz

**Comment by jbelien** [comment]
Awesome ! 👍 

I'll take care of the last steps later today.

**Comment by jbelien** [comment]
I have set up the automated data update process and deployment process ! 🚀 

You can now access your website here : https://halle-saale.equalstreetnames.eu/ (domain provided by the awesome @RobinLinde)

Now it's your job to update OpenStreetMap and Wikidata. 😄 
Everything will be automatically updated once a week on Thursday.

**Comment by hjoertel** [comment]
Am Donnerstag, 8. April 2021, 18:29:35 CEST schrieb Jonathan Beliën:
> I have set up the automated data update process and deployment process ! 🚀 
> 
> You can now access your website here : https://halle-saale.equalstreetnames.eu/ (domain provided by the awesome @RobinLinde)
> 
> Now it's your job to update OpenStreetMap and Wikidata. 😄 
> Everything will be automatically updated once a week on Thursday.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/EqualStreetNames/equalstreetnames/issues/163#issuecomment-815966551
> 

Hi Jonathan

looks not so good so far, Looks like we have to do a lot of work to make the result valid

Heinz
