### ISSUE TITLE
✨ New global map

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#167]
Just to let you know that I have upgraded the global map : https://equalstreetnames.be/

- Automated process (no need to add the city manually)
- Improved popup design
- Display of marker in low zoom levels (0 - 8)
- Display of boundary polygon(s) in high zoom levels (8+)
- Display of statistics in the popup

Feedback welcome !

Ping @EqualStreetNames/belgium @EqualStreetNames/germany @EqualStreetNames/netherlands @EqualStreetNames/serbia

**Comment by hjoertel** [comment]
Am Samstag, 10. April 2021, 16:24:37 CEST schrieb Jonathan Beliën:
> Just to let you know that I have upgraded the global map : https://equalstreetnames.be/
> 
> - Automated process (no need to add the city manually)
> - Improved popup design
> - Display of maker in low zoom levels (0 - 8)
> - Display of boundary polygon(s) in high zoom levels (8+)
> - Display of statistics in the popup
> 
> Feedback welcome !
> 
> Ping @EqualStreetNames/belgium @EqualStreetNames/germany @EqualStreetNames/netherlands @EqualStreetNames/serbia 
> 
>

Jonathan,

I' missing Halle in the list of German cities on the overview page


https://equalstreetnames.eu/de.html

Is it on me to make a change ?


Regards 	Heinz

**Comment by RobinLinde** [comment]
> Jonathan, I' missing Halle in the list of German cities on the overview page https://equalstreetnames.eu/de.html Is it on me to make a change ? Regards Heinz

The list on equalstreetnames.eu is served from [RobinLinde/EqualStreetNamesLanding](https://github.com/RobinLinde/EqualStreetNamesLanding), which I keep up-to-date manually. I have now added it in https://github.com/RobinLinde/EqualStreetNamesLanding/commit/d55b2506c10ac6a4166c05f322c0e548658de14a. 

It might be an idea to make equalstreetnames.eu serve the same page as equalstreetnames.be. @jbelien ?

**Comment by jbelien** [comment]
@hjoertel The "official" overview page is <https://equalstreetnames.be/> (built automatically from this repository). <https://equalstreetnames.eu/> is managed by @RobinLinde (see his comment here above).

---

> It might be an idea to make equalstreetnames.eu serve the same page as equalstreetnames.be. @jbelien ?

It is really as you wish! 😄 
<https://equalstreetnames.be/> is indeed now probably easier to maintain since it's built automatically.
Feel free to deploy the global map from this repository to <https://equalstreetnames.eu/> or redirect <https://equalstreetnames.eu/> to <https://equalstreetnames.be/>.

**Comment by hjoertel** [comment]
Am Freitag, 16. April 2021, 16:04:05 CEST schrieb Jonathan Beliën:

> 
> > It might be an idea to make equalstreetnames.eu serve the same page as equalstreetnames.be. @jbelien ?

Thanks to both of you.
I'm really not sure which landing page are better suited, .eu or .be

Regards
	Heinz

**Comment by RobinLinde** [comment]
Might make something new in the future, but for ease of maintenance I've opened a PR (#169)

**Comment by hjoertel** [comment]
Jonathan,


last week I did add a lot of adding wikidata information. BUT, i coudn't await the update on Thusday, i cant see the newly added street information on 
https://halle-saale.equalstreetnames.eu/

What went wrong?

Greetings
	Heinz

**Comment by RobinLinde** [comment]
EqualStreetNamesLanding now uses the `cities.json` file to generate the links, so it should stay up-to-date now.
