### ISSUE TITLE
New repository for Bern, the federal city of Switzerland

### ISSUE THREAD

**Issue by habi** [EqualStreetNames/equalstreetnames#171]
Awesome project, I saw it linked in the latest weeklyOSM!

I've created a repository for Bern, the <del>capital</del>federal city of Switzerland and would be happy to migrate it to the EqualStreetNames organization: https://github.com/habi/equalstreetnames-bern

**Comment by jbelien** [comment]
Awesome ! 🤩 
Welcome on board !

I have created a [Bern team](https://github.com/orgs/EqualStreetNames/teams/bern), you should have received an invitation to the team.

Once you joined the team you should be able to transfer your `equalstreetnames-bern` repository to EqualStreetNames organization.

Once it's done, I'll setup the automated update and deployment. 🚀

**Comment by habi** [comment]
> I have created a [Bern team](https://github.com/orgs/EqualStreetNames/teams/bern), you should have received an invitation to the team.

I did.
And it 'forced' me to finally set up 2FA for GitHub :)

> Once you joined the team you should be able to transfer your `equalstreetnames-bern` repository to EqualStreetNames organization.

I also just did that, see screenshot below.

<img width="666" alt="Screenshot 2021-04-19 at 14 47 41" src="https://user-images.githubusercontent.com/1651235/115238754-527dd080-a11e-11eb-97df-c66b6cc89d39.png">

**Comment by jbelien** [comment]
>  And it 'forced' me to finally set up 2FA for GitHub :)

😄 

---

I'll take care of the following steps later today:

- [x] Make you maintainer of the Bern's team
- [x] Give admin rights to Bern's repository for Bern's team
- [ ] Create Bern's sub-module
- [ ] Add automated data update process
- [ ] Add automated deployment process
- [ ] Add Bern to the list of the cities ([README](https://github.com/EqualStreetNames/equalstreetnames#readme) + [Global map](https://equalstreetnames.be/))

**Comment by jbelien** [comment]
Automated data update process is enabled !

```
Person: 1
  Female (cis): 1 (100.00 %)
  Male (cis): 0 (0.00 %)
  Female (trans): 0 (0.00 %)
  Male (trans): 0 (0.00 %)
  Intersex: 0 (0.00 %)
  Non-Binary: 0 (0.00 %)
  Multiple: 0 (0.00 %)
  Unknown: 0 (0.00 %)

Not a person: 894
```

Now it's your turn to update OpenStreetMap ! 🎉

**Comment by jbelien** [comment]
https://bern.equalstreetnames.eu/en/index.html 🚀

**Comment by habi** [comment]
> Now it's your turn to update OpenStreetMap ! 🎉

I'm on it: https://osm.li/0UI
7 ways done, looots more to go :)

**Comment by jbelien** [comment]
Awesome! 🤩 
And Good luck!

Data will be automatically updated every Thursday.
We can also run the data update process on demand if you want, just ping me (or run it yourself - see [`INSTALL.md`](https://github.com/EqualStreetNames/equalstreetnames/blob/master/INSTALL.md)).

**Comment by jbelien** [comment]
Hello @chatelao,

I saw that you started contributing to Bern, welcome on board.
Can I add you to @EqualStreetNames/bern team ?

**Comment by habi** [comment]
> Can I add you to @EqualStreetNames/bern team ?

Yes, please do :)
We've talked about it off GitHub and @chatelao would like to contribute.

**Comment by jbelien** [comment]
Invitation sent to @chatelao ; he will automatically have admin rights on https://github.com/EqualStreetNames/equalstreetnames-bern 👍

**Comment by chatelao** [comment]
Thanks for having me.
