### ISSUE TITLE
Ignore sidewalks

### ISSUE THREAD

**Issue by habi** [EqualStreetNames/equalstreetnames#172]
In Bern (see [1]) we have a bunch of sidewalks mapped along the streets with `footway=sidewalk`.
I think these ways should be ignored from display and analysis.

[1]: https://bern.equalstreetnames.eu/

**Comment by jbelien** [comment]
Your 2 suggestions are valid solutions !

Personally, I don't think sidewalks should be tagged with `name` or `name:etymology:wikidata` in OpenStreetMap.

But since it happens in Bern, I would indeed just filter those out in your Overpass query for Bern. 👍

**Comment by habi** [comment]
> Personally, I don't think sidewalks should be tagged with `name` or `name:etymology:wikidata` in OpenStreetMap.
> But since it happens in Bern, I would indeed just filter those out in your Overpass query for Bern. 👍

I personally also think that sidewalks don't need names, but the main sidewalk-maker here in Bern (with a total of 9000 changesets) did so :)
I'll filter out sidewalks, this seems the easiest solution, thanks for the input!
