### ISSUE TITLE
Halle (Saale) failed update ?

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#173]
Jonathan,

last week I did add a lot of adding wikidata information. BUT, i coudn't await the update on Thusday, i cant see the newly added street information on 
https://halle-saale.equalstreetnames.eu/

What went wrong?

Greetings
	Heinz

_Originally posted by @hjoertel in https://github.com/EqualStreetNames/equalstreetnames/issues/167#issuecomment-826060321_

**Comment by jbelien** [comment]
Hello @hjoertel ,

The data update happened correctly on Thursday 22/04 (see https://github.com/EqualStreetNames/equalstreetnames-halle-saale/commit/7d3afabc014162759e7e0e854479a0df06b0ffbd).

The deployment process also happened correctly on Thursday but for a reason that I can't explain it didn't used the latest data.
I've run the deployment process again and it's now fixed.

I'll keep the issue open until (at least) next week to see if everything happens correctly next Thursday on the next automated process run.

**Comment by hjoertel** [comment]
Am Samstag, 24. April 2021, 12:08:01 CEST schrieb Jonathan Beliën:
> Hello @hjoertel ,
> 
> The data update happened correctly on Thursday 22/04 (see https://github.com/EqualStreetNames/equalstreetnames-halle-saale/commit/7d3afabc014162759e7e0e854479a0df06b0ffbd).
> 
> The deployment process also happened correctly on Thursday but for a reason that I can't explain it didn't used the latest data.
> I've run the deployment process again and it's now fixed.
> 
> I'll keep the issue open until (at least) next week to see if everything happens correctly next Thursday on the next automated process run.
> 

Thank you,
now much more streets are on the map with Wikidata data.  I still need more regional people helping with improve it.

May be we have another issue. I selected German
https://halle-saale.equalstreetnames.eu/de/
but the pop-up window when a street is selected, displays the English entry

Thanks and Greetings 
	Heinz

**Comment by jbelien** [comment]
> May be we have another issue. I selected German
> https://halle-saale.equalstreetnames.eu/de/
> but the pop-up window when a street is selected, displays the English entry

You forgot to add German in the languages used by the process in your `config.php`.
```diff
- 'languages' => ['en'],
+ 'languages' => ['de', 'en'],
```
I have made the update (the process is currently running).

**Comment by jbelien** [comment]
Data update has completed and the automated deployment succeeded. ✅

**Comment by hjoertel** [comment]
Am Samstag, 24. April 2021, 16:53:57 CEST schrieb Jonathan Beliën:
> > May be we have another issue. I selected German
> > https://halle-saale.equalstreetnames.eu/de/
> > but the pop-up window when a street is selected, displays the English entry
> 
> You forgot to add German in the languages used by the process in your `config.php`.

Ohh, I'm sorry
but thanks.


> ```diff
> - 'languages' => ['en'],
> + 'languages' => ['de', 'en'],
> ```
> I have made the update (the process is currently running).
> 
> 


-- 
mit freundlichen Grüßen aus Halle (Saale)
       Heinz-Jürgen Oertel

**Comment by RobinLinde** [comment]
@jbelien
I think I'm seeing some similar problems for Assen. It looks like something like this is happening:
1. Data is updated and committed to city repo
2. Tries to update submodule, but fails because local version is out of date because another workflow pushed something.
3. Deploy and build is triggered and uses the old version of the submodule that is still referenced

A fix might be to pull the main repo just before pushing in the workflow.

**Comment by jbelien** [comment]
For reference: https://github.com/EqualStreetNames/equalstreetnames-assen/runs/2462988471?check_suite_focus=true#step:12:8

I also had the same issue for cities in Belgium.

I use the `ad-m/github-push-action` GItHub Action and it's indeed already a feature request (see https://github.com/ad-m/github-push-action/issues/84).

There is already a `git pull` in the process before the push (see [update-data.yml#L76](https://github.com/EqualStreetNames/equalstreetnames-assen/blob/master/.github/workflows/update-data.yml#L76)).
We could indeed add another `git pull` after the commit but even though it will probably reduce the number of time this issue happens, I don't think it will fix it.

While waiting it's implemented in `ad-m/github-push-action`, I suggest to set a "update calendar" for each city so 2 cities don't run at the same time.

Something like:

- Brusssels, Monday 1:00AM
- Braine-l'Alleud, Monday 2:00AM
- Brugge, Monday 2:30AM
- Gent, Monday 3:00AM
- Leuven, Monday 3:30AM
- Liège, Monday 4:00AM
- Mons, Monday 4:30AM
- Namur, Monday 5:00AM
- Nivelles, Monday 5:30AM
- Berlin, Tuesday 1:00AM
- Freising, Tuesday 1:30AM
- Halle (Saale), Tuesday 2:00AM
- Leipzig, Tuesday 2:30AM
- Munich, Tuesday 3:00AM
- Assen, Wednesday 1:00AM
- Groningen, Wednesday 1:30AM
- Belgrade, Thursday 1:00AM
- Bern, Friday 1:00AM

Since the process doesn't take more than 30 minutes, that should avoid the issue.
What do you think ?

**Comment by RobinLinde** [comment]
Seems like a good solution for now, we could also create our own fork of `ad-m/github-push-action` and implement it. Doesn't seem like something that would be too hard.

**Comment by jbelien** [comment]
I think we're back on track, all cities have successfully been updated this week.

**Comment by hjoertel** [comment]
Am Freitag, 7. Mai 2021, 09:23:57 CEST schrieb Jonathan Beliën:
> I think we're back on track, all cities have successfully been updated this week.



Thanks, Danke
 Heinz (equalstreetnames Halle)
