### ISSUE TITLE
Add "last updated" 

### ISSUE THREAD

**Issue by hjoertel** [EqualStreetNames/equalstreetnames#186]
As in the subject, would be helpful for street name maintainers having this information in the info box.

**Comment by jbelien** [comment]
That's a good idea!
I'll try to add that in the data process. 👍

**Comment by jbelien** [comment]
@EqualStreetNames 

You can now display "Last update: ..." in your interface.
You can already check it on https://equalstreetnames.brussels/ !
I've also updated the template so it will automatically appear in the new cities, you just have to copy-paste it to add it to your city.

```diff
+ <div class="small text-muted mt-2">
+     Last update: <span id="last-update"></span>
+ </div>
``` 
(see https://github.com/EqualStreetNames/equalstreetnames-template/commit/79a3b3361d5d48b36c8c45c70e4d5cff0ab99db1)

`statistics.json` and `sources.json` have also now been merged to `metadata.json`, so you will first need to run an update process to generate the `metadata.json`, then you can update your HTML files to add the last update and run the deployment process.
