### ISSUE TITLE
New city (Leiden, Netherlands) - PHP error? 

### ISSUE THREAD

**Issue by RMHogervorst** [EqualStreetNames/equalstreetnames#188]
I've added a new city and try to run the data update but it fails for some reason. I haven't used Php that much so I'm a bit confused if I'm doing something wrong or if the code is wrong.

Here is what I did:
* created a new repository for my city https://github.com/RMHogervorst/equalstreetnames-leiden based on the template
* following the steps of the template readme:  modified the config.php, and the index.html files.
* cloned this repository https://github.com/EqualStreetNames/equalstreetnames/
* `git submodules add blblabla` anyways...: in my local repository all the countries and cities including my new one are there (countries/netherlands/leiden countries/netherlands/assen, countries/netherlands/groningen and all of belgium, serbia, switserland, germany) 
* installed composer (brew install composer)
* inside the process folder run `composer run update-data -- --city=netherlands/leiden`

This is my error:
```
Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in FILEPATH_ON_MY_SYSTEM/equalstreetnames/process/Command/AbstractCommand.php on line 16
Script php process.php overpass handling the update-data event returned with error code 255
```

Is there a problem in composer? `Composer version 2.0.13 2021-04-27 13:11:08` 
Is there a crucial step I'm missing ?

**Comment by jbelien** [comment]
Hello @RMHogervorst ,

First things first: welcome on board!

You're indeed right, I used Typed Properties that appears in PHP 7.4 but still refer to PHP 7.2 and PHP 7.3 in `composer.json`.
I'll update the `composer.json` file.

You're probably using a version of PHP prior to PHP 7.4.
Please upgrade to PHP 7.4 or PHP 8.0 !

**Comment by RMHogervorst** [comment]
You're right! Macos ships a very old version of php! I'll try again with a new version 'brew install php'

**Comment by RMHogervorst** [comment]
oh god, you have to force macos to use a newer version. 
If anyone has the same issue: use brew to install a new version of php `brew install php`
This will tell you where that version is installed. 
Add that path to the PATH. So in your .bash_profile (or zsh config) 
Add a line like this: `export PATH=/usr/local/Cellar/php/8.0.5/bin:$PATH` this will put the php version of homebrew before the standard macos version. Check if you have  new version by first restarting the shell, or running the `export PATH` line I just mentioned. and call `which php` in your terminal to see if you have recent version. In my case it should read `/usr/local/Cellar/php/8.0.5/bin/php`

**Comment by RMHogervorst** [comment]
unfortunately this is not enough, I have  a new error! I think I'm not getting the correct data.
I get a `Uncaught DivisionByZeroError: Division by zero in PATHTOTHERIGHTFOLDER/equalstreetnames/process/Command/StatisticsCommand.php:123` So I guess it isn't downloading the right values? 

```
            $output->writeln([
                sprintf('Person: %d', $total),
                sprintf('  Female (cis): %d (%.2f %%)', $genders['F'], $genders['F'] / $total * 100),
                sprintf('  Male (cis): %d (%.2f %%)', $genders['M'], $genders['M'] / $total * 100),
                sprintf('  Female (trans): %d (%.2f %%)', $genders['FX'], $genders['FX'] / $total * 100),
                sprintf('  Male (trans): %d (%.2f %%)', $genders['MX'], $genders['MX'] / $total * 100),
                sprintf('  Intersex: %d (%.2f %%)', $genders['X'], $genders['X'] / $total * 100),
                sprintf('  Non-Binary: %d (%.2f %%)', $genders['NB'], $genders['NB'] / $total * 100),
                sprintf('  Multiple: %d (%.2f %%)', $genders['+'], $genders['+'] / $total * 100),
                sprintf('  Unknown: %d (%.2f %%)', $genders['?'], $genders['?'] / $total * 100),
                sprintf('Not a person: %d', $genders['-']),
            ]);
```

**Comment by RMHogervorst** [comment]
hmm it doesn't download the right roads
```
> php process.php geojson '--city=netherlands/leiden'
Generate GeoJSON files.
City: netherlands/leiden
Relations: 0 node(s), 0 way(s), 0 relation(s)
    0 [->--------------------------]
Ways: 0 node(s), 0 way(s), 0 relation(s)
    0 [->--------------------------]
```

**Comment by RMHogervorst** [comment]
I first used the wrong OSM relation, (there are 2 for leiden) and so the boundary and adminlevel did not match. It took several tries but now I have a better relation with corresponding adminlevel and it downloads streets!

**Comment by jbelien** [comment]
My guess concerning the `DivisionByZeroError` was indeed that there was no data to process.
I'll add an error and stop the process if it happens so we don't get the `DivisionByZeroError`.

**Comment by RMHogervorst** [comment]
Thanks for all the help! it seems to work really well now!

**Comment by jbelien** [comment]
My pleasure. 😃 

I've created a @EqualStreetNames/leiden team. in case you want to merge Leiden with the rest of the cities by transferring your repository under @EqualStreetNames organization. You'll of course stay admin of the repository if you decide to transfer it (see https://github.com/EqualStreetNames/equalstreetnames-template#integrate-your-city-to-the-project)

**Comment by RMHogervorst** [comment]
awesome! Yes I was going to open an issue for that, but it works just as well in this one!

**Comment by jbelien** [comment]
I'll make the process updates later today (or tomorrow):

- [ ] Enable automated data process
- [ ] Enable automated website deployment
- [ ] Add city to README
- [ ] Add city to global website (<https://equalstreetnames.be/>)

**Comment by RobinLinde** [comment]
Started [mapping](https://www.openstreetmap.org/changeset/104057123) as well...

**Comment by jbelien** [comment]
@RMHogervorst Could you already create a MAPBOX_TOKEN secret variable with your (valid) Mapbox token in your repository : https://github.com/EqualStreetNames/equalstreetnames-leiden/settings/secrets/actions/new ?

**Comment by RMHogervorst** [comment]
✅  done

**Comment by jbelien** [comment]
Website is live: https://leiden.equalstreetnames.eu/en/index.html 🚀 
---
Domain name `leiden.equalstreetnames.eu` is "offered" and managed by @RobinLinde.

**Comment by jbelien** [comment]
I think everything is up and running so I'll close this issue.
