### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS , https://munich.equalstreetnames.eu/

### ISSUE THREAD

**Issue by ynux** [EqualStreetNames/equalstreetnames#190]
When opening https://munich.equalstreetnames.eu/ , we get the error ERR_TOO_MANY_REDIRECTS . With both Firefox and Chrome, and even after deleting all cookies. Other cities work (Freising, Brussels).

**Comment by RobinLinde** [comment]
Should be fixed now, seems to be an error from the combination of Github Pages and Cloudflare (https://stackoverflow.com/questions/50145231/how-to-fix-err-too-many-redirects-on-custom-github-pages-domain).

**Comment by jbelien** [comment]
Not really related to the project itself since it was a domain name "misconfiguration".

It seems to be fixed ; thanks @RobinLinde .
I'll close the issue.
