### ISSUE TITLE
MapLibre link in the bottom right goes to Mapbox

### ISSUE THREAD

**Issue by habi** [EqualStreetNames/equalstreetnames#191]
The bottom right of the map shows the MapLibre logo, but the link actually goes to Mapbox, as you can see in the screenshot.

<img width="912" alt="Screenshot 2021-05-02 at 22 54 43" src="https://user-images.githubusercontent.com/1651235/116827551-c944b000-ab99-11eb-949e-d18c842a8ad5.png">

This is not only the case for Brussels, but also for [Bern](https://bern.equalstreetnames.eu/) and several other cities linked on https://equalstreetnames.eu/

**Comment by jbelien** [comment]
That's indeed still the case in the MapLibre library source code (see https://github.com/maplibre/maplibre-gl-js/blob/c47d053f010fe221a511a44a44333b5d29e447dc/src/ui/control/logo_control.js#L33).

I've commented on the open issue related to the logo : https://github.com/maplibre/maplibre-gl-js/issues/121#issuecomment-831017594
