### ISSUE TITLE
New repository for St. Gallen, Switzerland

### ISSUE THREAD

**Issue by 1-Byte** [EqualStreetNames/equalstreetnames#192]
After reading @habi's write-up on bringing EqualStreetNames to Berne, I thought I give it a go for [St. Gallen](https://en.wikipedia.org/wiki/St._Gallen). Coincidentally, some members of the parliament asked about the gender distribution of street names in January. Maybe we can even use some of the data for our mapping purposes (see 1-Byte/equalstreetnames-stgallen#1).

I'm happy to transfer the ownership of the repository to the organization or wait until some significant portion is mapped.

**Comment by jbelien** [comment]
That's AWESOME, welcome on board! 🎉 

I've sent you an invite to the @EqualStreetNames/st-gallen team.
Feel free to transfer your repository when it suits you. I'll take care of the last steps when it's transferred.

**Comment by jbelien** [comment]
I've setup the automated update process and prepared the automated deployment.

Could you add your [Mapbox token](https://docs.mapbox.com/help/getting-started/access-tokens/) in a `MAPBOX_TOKEN` secret variable here : https://github.com/EqualStreetNames/equalstreetnames-stgallen/settings/secrets/actions/new ?

**Comment by jbelien** [comment]
🚀 Lift off: https://stgallen.equalstreetnames.eu/

---

Domain name `stgallen.equalstreetnames.eu` is provided and managed by @RobinLinde 
Let us know if you want to use your own domain name.

**Comment by 1-Byte** [comment]
Thank you for the setup!

**Comment by habi** [comment]
Interesting that St. Gallen is currently at a 50/50 gender-split :)

**Comment by 1-Byte** [comment]
That's because the only reliable information I could find so far, is about the few streets that actually have a female namegiver ;) Unfortunately, I expect the number of male namegivers to grow substantively.

**Comment by habi** [comment]
> Unfortunately, I expect the number of male namegivers to grow substantively.

That will be undoubtedly the case, as in most cities.
