### ISSUE TITLE
Mapbox token

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#193]
Since we have more and more cities joining, which is awesome, Open Knowledge Belgium can't provide a Mapbox token for all the cities.

I've asked to the last 2 cities that joined us (@EqualStreetNames/leiden & @EqualStreetNames/st-gallen) to provide their own token.
The early cities also already provided their own token.

Could the 5 following cities provide their own token and follow the following steps ?
- [x] @EqualStreetNames/bern 
- [x] @EqualStreetNames/freising
- [x] @EqualStreetNames/halle-saale 
- [ ] @EqualStreetNames/leipzig 
- [ ] @EqualStreetNames/munich 

Steps to follow:
1. Create a Mapbox account if you don't have one already : <https://account.mapbox.com/auth/signup/>
2. Create a token : <https://account.mapbox.com/access-tokens/>
3. Update the `MAPBOX_TOKEN` in your repository secret variables with your token
    Go to "Settings > Secrets > Repository secrets > MAPBOX_TOKEN > Update" in your repository
    - Leipzig: <https://github.com/EqualStreetNames/equalstreetnames-leipzig/settings/secrets/actions/MAPBOX_TOKEN>
    - Munich: <https://github.com/EqualStreetNames/equalstreetnames-munich/settings/secrets/actions/MAPBOX_TOKEN>
4. Comment here once it's done so I can check everything is working fine and delete the token provided by Open Knowledge Belgium

Here is the Mapbox documentation about tokens : <https://docs.mapbox.com/help/getting-started/access-tokens/>

Thanks!

**Comment by habi** [comment]
EqualStreetNames/bern has it's own access token in `MAPBOX_TOKEN`

**Comment by jbelien** [comment]
Thanks @habi !
I've deployed https://bern.equalstreetnames.eu/ using your token and deleted token provided by Open Knwoledge Belgium.
Everything is working fine!

**Comment by hjoertel** [comment]
Hope I filled it correctly for Halle-Saale, please check - and thanks

Heinz

**Comment by jbelien** [comment]
Thanks @hjoertel ! Everything is working fine ! 👍

**Comment by jbelien** [comment]
Ping @zorae @imlabormitlea-code @ynux @mitmirzutun , could you please have a look at this ? Dankeschön !

**Comment by zorae** [comment]
@jbelien changed Mapbox token for Freising. Please confirm

**Comment by jbelien** [comment]
It's been a month so I deleted Open Knowledge Belgium token used by Munich and Leipzig and opened dedicated issue in their own repository. Baselayer for those cities is now not displaying anymore (until the Mapbox token is updated).

**Comment by imlabormitlea-code** [comment]
Hei,
sorry for being that late. Was a bit of a busy time and I'm sorry having disappointed you Jonathan with being unreliable. I've added a token now. Is everything alright with it?
Best Lea

**Comment by jbelien** [comment]
No worries, danke @imlabormitlea-code ! Everything is back on track for https://leipzig.equalstreetnames.eu/ 👍

**Comment by ynux** [comment]
Sorry that we are so late, i overlooked the message. Updated it now.

**Comment by jbelien** [comment]
@ynux No worries, everything is fixed now : https://munich.equalstreetnames.eu/
