### ISSUE TITLE
Add Lausanne, Switzerland

### ISSUE THREAD

**Issue by eginhard** [EqualStreetNames/equalstreetnames#194]
After Bern and St. Gallen, I'd like to make a start in French-speaking Switzerland as well and created a repository for Lausanne: https://github.com/eginhard/equalstreetnames-lausanne

I can transfer this to the organisation.

**Comment by RobinLinde** [comment]
First of all, Welcome on board 🎉
Everything seems to look good.
@jbelien will send you an invite for a new team soon, and setup automated deployment.
Ive currently 'reserved' the domain `lausanne.equalstreetnames.eu` , let us know if you want to use another domain.

**Comment by jbelien** [comment]
Welcome on board @eginhard !

I've sent you an invite to @EqualStreetNames/lausanne !

**Comment by eginhard** [comment]
Thank you both (and @habi for spreading the word)! I've transferred the repository.

The domain sounds good.

**Comment by jbelien** [comment]
I'll take care of the last updates later today :)

**Comment by jbelien** [comment]
Here we go: https://lausanne.equalstreetnames.eu/ 🚀

**Comment by eginhard** [comment]
Beautiful, thank you!
