### ISSUE TITLE
Add link to edit OpenStreetMap directly from the website

### ISSUE THREAD

**Issue by nitramwin** [EqualStreetNames/equalstreetnames#195]
Hi, just a small idea but it would be helpful for the project (and for those looking at the maps) to more quickly add the tags from the main your_city.equalstreetnames.eu site. 

One option could be to link to iD on the bottom right of the page. 
Even better would be to have an edit button directly on the name of the street has clicked on. In the little dialog box, a link to iD with a pre-filled suggestion of the new tag to be added could speed up progress.

**Comment by jbelien** [comment]
Hello @nitramwin ,

That's indeed an excellent idea and would be helpful for the project but it's (currently) out of the scope of the project.

That being said, any help to make it happen is more than welcome.

**Comment by RobinLinde** [comment]
To be honest I have been thinking of building a dedicated editor, and have some ideas about how that should function.
Somethin simple like a list of streets, a detail page where you select a wikidata entry and just go to the next one.
The hardest thing is finding the time to do it...

**Comment by RobinLinde** [comment]
<img width="219" alt="firefox_YwJyZm7mr5" src="https://user-images.githubusercontent.com/1395345/117144245-fec3e600-adb1-11eb-980a-05b157db1be3.png">

https://github.com/EqualStreetNames/equalstreetnames/commit/d7d6e9dd69e465dd31d5812e06590347838fdf3e implements a basic version without any regards for element type (or code quality).

**Comment by jbelien** [comment]
I like it but I would try to keep it a bit more "hidden", a regular user is probably not interested by that function.
Also see https://github.com/EqualStreetNames/equalstreetnames/commit/d7d6e9dd69e465dd31d5812e06590347838fdf3e#r50417173

**Comment by RobinLinde** [comment]
<img width="374" alt="firefox_HvpqdzEBkP" src="https://user-images.githubusercontent.com/1395345/117309469-bb857800-ae82-11eb-923b-5dabd752b289.png">

I've now got a basic 'editor' that takes an OSM way or relation, gets associated tags and tries to provide a suggestion for a Wikidata entry.  Now it just needs to add the info to OSM...

**Comment by RobinLinde** [comment]
<img width="251" alt="firefox_E6SBWpgfVh" src="https://user-images.githubusercontent.com/1395345/117441038-2099a600-af35-11eb-97fd-0649bbeca5bb.png"><img width="241" alt="firefox_iZxHFLWKY0" src="https://user-images.githubusercontent.com/1395345/117441094-2ee7c200-af35-11eb-8c8a-03cf3aa1483c.png">

Able to make changesets now as well, just need to sort out some more error handling and quite a few usability improvements.

**Comment by jbelien** [comment]
Nice ! Well done @RobinLinde ! 👍 

I would also maybe add a `#equalstreetnames` hashtag to the changeset comment so we can easily check the changesets if needed.

**Comment by RobinLinde** [comment]
Rewrote the complete changeset code today, also includes `#equalstreetnames` in the commment (https://master.apis.dev.openstreetmap.org/changeset/215178). Will publish the code probably later today, have been having some trouble to get it to build properly earlier. Still haven't improved usability that much. Right now the only feedback on whether an edit succeeded is some vague message in the console.

**Comment by RobinLinde** [comment]
Later today has arrived 😉, I published it over at [RobinLinde/ESN-edit](https://github.com/RobinLinde/ESN-edit). Still needs the same updates though 😐.

**Comment by jbelien** [comment]
Looking good, let us know when you're looking for feedback ! :)

**Comment by RobinLinde** [comment]
Just made the first changeset on production server: https://www.openstreetmap.org/changeset/104702072. The version on [edit.equalstreetnames.eu](https://edit.equalstreetnames.eu) should be working enough to do some edits.

There is still a lot of room for improvement, for example the [list](https://github.com/RobinLinde/ESN-edit/blob/master/src/index.ts#L83) of common words it filters isn't that complete. It would probably be a good idea to allow the user to alter the search term, as well as the search language, which currently defaults to English.

As always, any feedback, comments or other remarks is very welcome.

**Comment by jbelien** [comment]
Awesome work @RobinLinde ! 👍 

I suggest we close this issue here and use issues on your repository (https://github.com/RobinLinde/ESN-edit/issues).

**Comment by RobinLinde** [comment]
Might be worth to keep this open, while I do now have a basic editor, there is no proper implementation of a link yet...
Any other issues or problems can indeed be raised there (https://github.com/RobinLinde/ESN-edit), I've also enabled discussions there, seems like a good idea.

**Comment by jbelien** [comment]
> [...] there is no proper implementation of a link yet...

Fair point!

**Comment by RobinLinde** [comment]
![popup](https://user-images.githubusercontent.com/1395345/119230840-2d65ee80-bb1e-11eb-8130-02aa4d18b20e.png)
![popup](https://user-images.githubusercontent.com/1395345/119230854-41115500-bb1e-11eb-912a-81a17f4f8f99.png)

I have a new, more subtle version of an edit link, that still needs some refinement over in #200.

**Comment by jbelien** [comment]
Nice, I was indeed thinking something like that. 👍

**Comment by jbelien** [comment]
Link will appear automatically after next update for each city ! 🚀
