### ISSUE TITLE
Add Brandenburg an der Havel, Germany

### ISSUE THREAD

**Issue by Itchiii** [EqualStreetNames/equalstreetnames#198]
After @hjoertel mapped the key, I got curious and wanted to try the project in my city. Unfortunately, the tag has not yet been used, so I still have a lot to do. But I am also attracted by the historical aspect.

I would like to transfer the project then. Let me know if something is missing or I should do something. I have already created a MAPBOX_TOKEN in the settings.

Repo: https://github.com/Itchiii/equalstreetnames-brandenburg-an-der-havel

A small thing, because in my city the key was not used yet, I got an error (division by zero) with the command `composer run update-data`.

**Comment by jbelien** [comment]
Awesome! 🎉 

I've created a "Brandenburg an der Havel" team so you should be able to transfer your repository.
I'll take care of the last steps once it's transferred.

**Comment by Itchiii** [comment]
> I've created a "Brandenburg an der Havel" team so you should be able to transfer your repository.

Done

**Comment by jbelien** [comment]
Thanks, I'll take care of the next steps later today :)

**Comment by jbelien** [comment]
There you go : https://brandenburg-an-der-havel.equalstreetnames.eu/ 🚀 

Domain name is provided and managed by @RobinLinde. Let us know if you want to setup your own domain name.

**Comment by RobinLinde** [comment]
@jbelien Great! I've already added data to some more streets to test ESN-edit a bit more and added `platz` to the list of common words.
