### ISSUE TITLE
Update the style of the website

### ISSUE THREAD

**Issue by wjtje** [EqualStreetNames/equalstreetnames#202]
Currently the website uses a mix of light and dark colors,
it would be nice if the site was more consistent.

### Currently

![image](https://user-images.githubusercontent.com/33957974/119635986-7ebef800-be14-11eb-9522-f0cbd0efa89f.png)

### Full dark mode

![image](https://user-images.githubusercontent.com/33957974/119636045-8f6f6e00-be14-11eb-80fa-56b0f4fffbce.png)

### Full dark mode with backdrop filter

![image](https://user-images.githubusercontent.com/33957974/119636892-613e5e00-be15-11eb-8f59-155e0358ec18.png)

**Comment by jbelien** [comment]
That's indeed a nice idea, thanks @wjtje ! 👍 
I would even suggest to use the browser theme (dark/light) by default with a button to switch to the other theme.

Would you have time to submit a PR for this ?

**Comment by wjtje** [comment]
I've got the browser theme working now but implementing the button to switch the theme and changing the map theme would require modification to each city's index.html.

**Comment by jbelien** [comment]
> [...] would require modification to each city's index.html

Definitely not an issue!
You can update the `index.html` file from the [template](https://github.com/EqualStreetNames/equalstreetnames-template) (with another PR).
Each city will then decide if they apply the update or not.
