### ISSUE TITLE
Zurich repository ready for adding

### ISSUE THREAD

**Issue by CaptainInler** [EqualStreetNames/equalstreetnames#204]
[Zurich (Q72)](https://www.wikidata.org/wiki/Q72) would be happy to be a part on this project.. :-)
The repo to copy is here: https://github.com/CaptainInler/equalstreetnames-zurich

**Comment by habi** [comment]
Awesome @CaptainInler :)

*Happy to have helped with the initial setup*

**Comment by jbelien** [comment]
Awesome ! Welcome @CaptainInler !

I've sent you an invite to join @EqualStreetNames/zurich !
Once you joined the team you will be able to transfer the repository (if you choose to do so).

**Comment by CaptainInler** [comment]
@jbelien Thank you for the invitation. Transfering the repo is on its way. Hopefully I did it right...

**Comment by jbelien** [comment]
You did it right ! 👍 

I'll take care of the next steps later today.

**Comment by jbelien** [comment]
@CaptainInler Don't forget to add your `MAPBOX_TOKEN` here : https://github.com/EqualStreetNames/equalstreetnames-zurich/settings/secrets/actions/new

**Comment by habi** [comment]
@CaptainInler:  > Don't forget to add your `MAPBOX_TOKEN`

This was the 'thing' that I mentioned yesterday that is not specified in the template :)
Details are specified here: https://github.com/EqualStreetNames/equalstreetnames/issues/193

**Comment by CaptainInler** [comment]
```MAPBOX_TOKEN``` is created 👍

**Comment by jbelien** [comment]
> This was the 'thing' that I mentioned yesterday that is not specified in the template :)

I'll indeed update the README with that information. 👍

**Comment by jbelien** [comment]
There you go : https://zurich.equalstreetnames.eu/ 🚀

**Comment by CaptainInler** [comment]
@jbelien could you please add sstuder to the zurich team?

**Comment by jbelien** [comment]
Sure, I've sent the invite to @sstuder 😃 

You're "maintainer" of @EqualStreetNames/zurich , you also have the right to add/remove members: https://github.com/orgs/EqualStreetNames/teams/zurich/members

**Comment by CaptainInler** [comment]
Thanks for sending the invitation :raised_hands:
As far as I see, it is not possible for me to add members who are not member of the organisation. Thats the message when I try to add members:
![add member message](https://user-images.githubusercontent.com/16583617/120890072-dd4c5900-c600-11eb-9a55-7ec6a1c6d67d.png)

**Comment by jbelien** [comment]
@CaptainInler Sorry about that, you're absolutely right.

I misunderstood the permissions allowed for a team maintainer.
It's indeed limited to "Add organization members to the team" (see https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/giving-team-maintainer-permissions-to-an-organization-member)
