### ISSUE TITLE
Add Dresden, Germany

### ISSUE THREAD

**Issue by Itchiii** [EqualStreetNames/equalstreetnames#206]
Here we go with Dresden: https://github.com/Itchiii/equalstreetnames-dresden

Mapbox Token is set.

I had adjusted the overpass queries to exclude ways in "Dresdner Heide", because they are named with numbers or refs. But not are officials streets. If I found a way with a name of a person in Dresdner Heide, I will add it manually in overpass to show it on map. It is not enough if this particular path is written in the config or in data.csv, is it?

But maybe you look over it, if you know how to do an overpass query in the most performant way. https://github.com/Itchiii/equalstreetnames-dresden/blob/master/overpass/relation-full-json

**Comment by jbelien** [comment]
Nice, you've been added to @EqualStreetNames/dresden !

I'll setup the automated process once the repository is migrated.

> I had adjusted the overpass queries to exclude ways in "Dresdner Heide", because they are named with numbers or refs. But not are officials streets.

Maybe you could just filter out all the `highway=path`.
You could also use the `exclude` arrays in `config.php`.

> It is not enough if this particular path is written in the config or in data.csv, is it?

Indeed, if the relation or way is not fetched by the Overpass query, it will not be processed (no matter if it's referenced in `config.php` or `data.csv` or not).

**Comment by Itchiii** [comment]
> I'll setup the automated process once the repository is migrated.

Repo is transferred.

> Maybe you could just filter out all the highway=path.

At the moment I take all path and tracks from the Dresdner Heide. If I do this all over Dresden, then definitely paths named after people will be excluded.

> You could also use the exclude arrays in config.php.

This affects over 200 paths, so the effort would be very high.

**Comment by jbelien** [comment]
🚀 <https://dresden.equalstreetnames.eu>
