### ISSUE TITLE
Build failing for Assen, Groningen and Munich

### ISSUE THREAD

**Issue by RobinLinde** [EqualStreetNames/equalstreetnames#236]
Build fails and gives an empty result, error seems to be in the main `index.html`.
`/XX/index.html` should be `./XX/index.html`, will fix it for Assen and Groningen, but probably also needs to be done for @EqualStreetNames/munich.

**Comment by jbelien** [comment]
Thanks for the notice!
I'll have a look ASAP !

**Comment by jbelien** [comment]
Everything is back on track !
Fix has been deployed.
