### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#27]
Following the restructure (f157bfb11234a4a65ee16b275abd0c8f66dbb3d1), the documentation needs to be updated/fixed !

---

- [x] Finish `geojson.php` script documentation
- [ ] Write `statistics.php` script documentation

**Comment by mitmirzutun** [comment]
I cloned the repository with the git clone command (`git clone https://github.com/openknowledgebe/equalstreetnames.git`) in the documentation to run on my computer and it didn't clone the submodules.
It cloned correctly with `git submodule init` followed by `git submodule update --recursive` within the cloned directory (taken from git-scm.com/docs/git-submodule) or clone everything with `git clone --recursive https://github.com/openknowledgebe/equalstreetnames.git`

**Comment by jbelien** [comment]
Hello @mitmirzutun, indeed, each city is a sub-module !
You can find all documentation on how to work with sub-modules here: <https://git-scm.com/book/en/v2/Git-Tools-Submodules>.
