### ISSUE TITLE
Warsaw, Poland

### ISSUE THREAD

**Issue by starsep** [EqualStreetNames/equalstreetnames#293]
Repo is here: https://github.com/starsep/equalstreetnames-warsaw
I would like to `Transfer your repository to the EqualStreetNames organization.` with `an automated data update`.

Current stats: (I intend to improve the OSM data in the near future)
Male (cis) | 51 | 92.73 %
Female (cis) | 4 | 7.27 %
Male (trans) | 0 | 0 %
Female (trans) | 0 | 0 %
Out of 5533 streetnames, 55 (0.99%) have been found to be named after a person.

**Comment by jbelien** [comment]
Awesome! Welcome on board @starsep !

I've sent you an invite to @EqualStreetNames/warsaw ; once you accept it, you'll be able to transfer your repository, then I'll take care of the next steps.

**Comment by jbelien** [comment]
The automated update is [running](https://github.com/EqualStreetNames/equalstreetnames-warsaw/actions/workflows/update-data.yml) and will be automatically triggered every Thursday at 7:00 UTC.

The automated deployment is [setup](https://github.com/EqualStreetNames/equalstreetnames-warsaw/actions/workflows/deploy.yml) and will be automatically triggered after each update.

**Comment by jbelien** [comment]
🚀 https://warsaw.equalstreetnames.eu/
