### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by RobinLinde** [EqualStreetNames/equalstreetnames#302]
Got a push-notification that Brandenburg, Dresden, Freising, Halle, Leipzig and Munich seem to be down. Looks like the build failed ([example for Dresden](https://github.com/EqualStreetNames/equalstreetnames-dresden/runs/3346915923?check_suite_focus=true#step:5:11)), but the build step succeeded, deploying an empty site.

**Comment by jbelien** [comment]
Thanks for the notification @RobinLinde !

I guess it's caused by one of the dependency updates from yesterday.
I'll investigate ASAP.

**Comment by jbelien** [comment]
Okay, issue was caused by the upgrade of Parcel from 2.0.0-beta.2 to 2.0.0-rc.0 ! 🐛 

I fixed it for Brussels now I have to check/fix all the other cities.

**Comment by jbelien** [comment]
- [x] belgium/brussels
- [ ] belgium/braine-lalleud
- [ ] belgium/brugge
- [ ] belgium/gent
- [ ] belgium/leuven
- [ ] belgium/liege
- [ ] belgium/mons
- [ ] belgium/namur
- [ ] belgium/nivelles
- [ ] germany/berlin
- [ ] germany/freising
- [ ] germany/halle-saale
- [ ] germany/leipzig
- [ ] germany/munich
- [ ] germany/brandenburg-an-der-havel
- [ ] germany/dresden
- [ ] netherlands/assen
- [ ] netherlands/groningen
- [ ] netherlands/leiden
- [ ] serbia/belgrade
- [ ] slovakia/bratislava
- [ ] poland/warsaw
- [ ] switzerland/bern
- [ ] switzerland/stgallen
- [ ] switzerland/lausanne
- [ ] switzerland/zurich
- [ ] spain/madrid
- [ ] italy/bolzano
- [ ] france/saint-brieuc
- [ ] luxembourg/luxembourg
- [ ] usa/sanfrancisco
- [ ] austria/vienna
- [ ] belarus/minsk
- [ ] united-kingdom/chester-le-street
- [ ] philippines/sanpablo

**Comment by jbelien** [comment]
https://github.com/EqualStreetNames/equalstreetnames-template has also been fixed.

**Comment by jbelien** [comment]
@RobinLinde Thanks again for the notice! Everything should be back on track!

I'll keep an eye on the weekly updates in the following days.
Keep me updated if something is still broken by reopening this issue.
