### ISSUE TITLE
Freiburg im Breisgau, Germany

### ISSUE THREAD

**Issue by Sequynth** [EqualStreetNames/equalstreetnames#303]
Hey, I started to add wikidata to streets in Freiburg. Please add my repository to the project: https://github.com/Sequynth/equalstreetnames-freiburg-im-breisgau

**Comment by jbelien** [comment]
Welcome on board @Sequynth !

I've sent you an invite to @EqualStreetNames/freiburg-im-breisgau ; once you've accepted the invite you should be able to transfer your repository.

**Comment by Sequynth** [comment]
I cant find the invite (full disclosure: I also dont know where to look)

**Comment by jbelien** [comment]
You should have received an email.
You can also try https://github.com/orgs/EqualStreetNames/invitation

**Comment by jbelien** [comment]
I'll take care of the next steps!

Meanwhile could you add your `MAPBOX_TOKEN` in the repo secrets (see https://github.com/EqualStreetNames/equalstreetnames-template#integrate-your-city-to-the-project)

**Comment by jbelien** [comment]
You can follow the progress of the deployment here: #306

**Comment by jbelien** [comment]
🚀 https://freiburg-im-breisgau.equalstreetnames.eu/
