### ISSUE TITLE
Chorzów, Poland

### ISSUE THREAD

**Issue by ArturLange** [EqualStreetNames/equalstreetnames#308]
Repo is here: https://github.com/ArturLange/equalstreetnames-chorzow
I would like to `Transfer your repository to the EqualStreetNames organization` with `an automated data update`.

Male (cis) | 124 | 91.85 %
Female (cis) | 11 | 8.15 %
Male (trans) | 0 | 0 %
Female (trans) | 0 | 0 %

Out of 400 streetnames, 135 (33.75%)have been found to be named after a person.

**Comment by jbelien** [comment]
Awesome!

You should have received an invitation to join @EqualStreetNames/chorzow.
Once you joined the team, you will be able to transfer your repository.

If it's not already done, don't forget to add your `MAPBOX_TOKEN` secret.

**Comment by ArturLange** [comment]
Accepted and transferred.
Can't add secrets yet though.
`MAPBOX_TOKEN` should be set in GitHub secrets, right?

**Comment by ArturLange** [comment]
Thank you!
Added it.

**Comment by jbelien** [comment]
Deployment to https://chorzow.equalstreetnames.eu/ is on its way!

**Comment by jbelien** [comment]
Done! 🚀
