### ISSUE TITLE
Adding Mainz, Germany

### ISSUE THREAD

**Issue by vwestric** [EqualStreetNames/equalstreetnames#327]
Hello, we would like to add the city of Mainz  to your project by transferring ownership to you. Here is our repository: https://github.com/BerenikeRe/equalstreetnames-mainz

**Comment by jbelien** [comment]
Awesome! Welcome on board @vwestric !

You should have received an invite to join @EqualStreetNames/Mainz.
Once you join the team you should be able to transfer your repository to @EqualStreetNames organization.

**Comment by jbelien** [comment]
I also sent an invite to @BerenikeRe to join @EqualStreetNames/mainz.

Who will be the "main" maintainer ?

**Comment by vwestric** [comment]
@jbelien Thank you! @BerenikeRe will be main maintainer.

**Comment by BerenikeRe** [comment]
I transferred the repository to EqualStreetNames.

**Comment by jbelien** [comment]
Thanks! I'll take of the next few steps ASAP in the next few days. 😃

**Comment by jbelien** [comment]
Here you go : https://mainz.equalstreetnames.eu/ 🚀
