### ISSUE TITLE
Recently updated websites are not available

### ISSUE THREAD

**Issue by Sequynth** [EqualStreetNames/equalstreetnames#340]
Repositories that have been updated recently are not acessible from the web using https://cityname.equalstreetnames.eu/

e.g. Leiden, Groningen, Assen, Mainz, Freiburg im Breisgau, ...

**Comment by jbelien** [comment]
Thanks for the notice @Sequynth ; I'll have a look ASAP (probably this weekend).

**Comment by RobinLinde** [comment]
Should (at least partially) be fixed by this PR in Parcel: https://github.com/parcel-bundler/parcel/pull/6784 Related issue: https://github.com/parcel-bundler/parcel/issues/6893

**Comment by chatelao** [comment]
Thanks @RobinLinde and @jbelien for having a look - Greetings from Bern

**Comment by jbelien** [comment]
Thanks @RobinLinde for you Pull Request (#339), that should avoid me breaking everything by upgrading a library.
I downgraded the libraries that were causing the issue.
Everything should be back in a few days when the next update is triggered !
I'll keep this issue open until then.

**Comment by Sequynth** [comment]
Yes, looks good to me too. Thanks! :)

**Comment by chatelao** [comment]
Great - Thank you very much
