### ISSUE TITLE
Geojsons served without gzip compression

### ISSUE THREAD

**Issue by starsep** [EqualStreetNames/equalstreetnames#354]
It seems that geojsons are served without gzip compression at *.equalstreetnames.eu
![image](https://user-images.githubusercontent.com/2798728/135733761-946dada8-6ec4-4400-8af2-dc5ef26740b4.png)
![image](https://user-images.githubusercontent.com/2798728/135733728-0d06357c-427f-4a50-8e6a-ba0c55d76f87.png)
![image](https://user-images.githubusercontent.com/2798728/135733730-d7b8b923-b2ec-46ae-bd3e-7abe830f9603.png)
![image](https://user-images.githubusercontent.com/2798728/135733733-de3916c2-84bb-4305-b84b-50a47a9567c0.png)
![image](https://user-images.githubusercontent.com/2798728/135733736-1363829d-dbcb-496e-844f-058f9c40cbdd.png)
![image](https://user-images.githubusercontent.com/2798728/135733740-f81b976e-a10d-47e2-a69e-1ba88314f388.png)
![image](https://user-images.githubusercontent.com/2798728/135733742-a438eac1-81bb-4f07-957a-44cb8a526578.png)

minsk.equalstreenames.org, brugge.equalstreetnames.be and equalstreetnames.brussels work fine
![image](https://user-images.githubusercontent.com/2798728/135733745-b4c2e1fa-08f1-467c-8a34-0128963e8cce.png)
![image](https://user-images.githubusercontent.com/2798728/135733717-5c840a4c-a54c-400a-87a4-8ed693bfb79a.png)
![image](https://user-images.githubusercontent.com/2798728/135733748-15f33498-7aa2-4cc9-8c7d-00b33f545576.png)

Looking at headers Cloudflare is used.
Possibly just a matter of configuration as `application/geo+json` is not on the list of content types gzipped by default at https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

Also naziviulica.openstreetmap.rs is affected but that's 3rd party issue discussed in #25, right?
![image](https://user-images.githubusercontent.com/2798728/135733713-ee7d0eb0-435f-401a-b80f-18bf98577056.png)

**Comment by jbelien** [comment]
The `equalstreetnames.eu` subdomains are the only one using Cloudlflare proxy and that's indeed probably why it's not compressed.

I'll update the Cloudflare configuration and disable the proxy so all websites hosted on GitHub pages are handled the same way.

`naziviulica.openstreetmap.rs` is managed by @stalker314314 , you should check with him.
