### ISSUE TITLE
Pop-Up fails on Squares

### ISSUE THREAD

**Issue by CaptainInler** [EqualStreetNames/equalstreetnames#377]
Pop-Up fails to show on Squares.
EG: 
- https://www.openstreetmap.org/way/892888816
- https://www.openstreetmap.org/way/41832665
- https://www.openstreetmap.org/way/776702917

Browserconsole Error:
`Uncaught Error: Unimplemented type: 4`

**Comment by jbelien** [comment]
THanks @CaptainInler, I'll have a look.

**Comment by jbelien** [comment]
I've upgraded the dependencies and rebuilt https://zurich.equalstreetnames.eu//
It seems to be fixed ; re-open this ticket if the issue is still there.
