### ISSUE TITLE
Adding Rastede, Germany

### ISSUE THREAD

**Issue by u6CqmdfBgm** [EqualStreetNames/equalstreetnames#379]
Hi, I would like to add the city of Rastede to your project by transferring ownership to you. Here is my repository: https://github.com/u6CqmdfBgm/equalstreetnames-rastede That's my first steps with github, I hope anything is fine.

**Comment by u6CqmdfBgm** [comment]
Hi, do you need any more information? Or is anything fine?

**Comment by jbelien** [comment]
Hello @u6CqmdfBgm ,

Welcome on board.
You've been invited to join @EqualStreetNames/rastede 
Once you joined the team, you'll be able to transfer the ownership of your repository to @EqualStreetNames.

I'll take care of the next steps when your repository is transfered and I have some free time.

**Comment by u6CqmdfBgm** [comment]
Hi, I transferred the repository to EqualStreetNames. Thank you.

**Comment by jbelien** [comment]
Perfect, I'll take care of the next steps when I have some free time.

**Comment by jbelien** [comment]
🚀 Deployed: https://rastede.equalstreetnames.eu/
