### ISSUE TITLE
Add Wiesbaden, Germany

### ISSUE THREAD

**Issue by mattsches** [EqualStreetNames/equalstreetnames#396]
Hi, I'd like to add Wiesbaden, Germany to this wonderful project. The repo can be found here: https://github.com/mattsches/equalstreetnames-wiesbaden

**Comment by jbelien** [comment]
Hello @mattsches, you should have received an invite to join @EqualStreetNames/wiesbaden.

Once you've joined you should be able to transfer your repository.

**Comment by mattsches** [comment]
Repository transfered!

**Comment by jbelien** [comment]
Perfect, I'll take care of the next steps when I have some free time.

**Comment by mattsches** [comment]
Thank you! :smiley:

**Comment by jbelien** [comment]
🚀 Deployed: https://wiesbaden.equalstreetnames.eu/
