### ISSUE TITLE
Pop-up is not displayed

### ISSUE THREAD

**Issue by Itchiii** [EqualStreetNames/equalstreetnames#410]
After clicking on some streets (cursor: pointer), no popup appears. The console shows the following error.

You can test it here on "[Spittastraße](https://brandenburg-an-der-havel.equalstreetnames.eu/de/index.html#16.7/52.415904/12.529427)"

```
Uncaught TypeError: t.name is undefined
    i popup.ts:14
    default popup.ts:115
    default events.ts:4
    default events.ts:12
    fire evented.js:117
    click map_event.js:53
    handleEvent handler_manager.js:344
    addEventListener dom.js:94
    yn handler_manager.js:174
    n map.js:453
    default map.ts:63
    l map.ts:29
    s map.ts:12
    default map.ts:7
    default map.ts:2
    default map.ts:7
    l theme.ts:7
    default theme.ts:24
popup.ts:14:29
    i popup.ts:14
    default popup.ts:115
    default events.ts:4
    default events.ts:12
    fire evented.js:117
    click map_event.js:53
    handleEvent handler_manager.js:344
    <anonym> self-hosted:1178
    (Async: EventListener.handleEvent)
    addEventListener dom.js:94
    yn handler_manager.js:174
    n map.js:453
    default map.ts:63
    l map.ts:29
    s map.ts:12
    default map.ts:7
    default map.ts:2
    default map.ts:7
    l theme.ts:7
    default theme.ts:24
```

**Comment by jbelien** [comment]
I've upgraded the dependencies and rebuilt https://brandenburg-an-der-havel.equalstreetnames.eu/
It seems to be fixed ; re-open this ticket if the issue is still there.

**Comment by Itchiii** [comment]
Also appears on other pages like: https://dresden.equalstreetnames.eu/ and https://leipzig.equalstreetnames.eu/
Maybe more pages need a rebuild.

**Comment by jbelien** [comment]
Fair point!
I've updated Dresden and Leipzig but there are now too many cities to do it all by myself.
All the maintainers can re-run the last "Deploy" GitHub Actions workflow to rebuild the website.

Otherwise, it will be automatically rebuild with the next data update next month (01/02 and 02/02).
