### ISSUE TITLE
Mousemove Error

### ISSUE THREAD

**Issue by Itchiii** [EqualStreetNames/equalstreetnames#411]
If I move the mouse over the map. The console is full of errors:

* `Uncaught Error: Unimplemented type: 6` and type 3, 4 and 5
* `Uncaught Error: unknown command 5`

Tested here: https://brandenburg-an-der-havel.equalstreetnames.eu/de/index.html

**Comment by jbelien** [comment]
I've upgraded the dependencies and rebuilt https://brandenburg-an-der-havel.equalstreetnames.eu/
It seems to be fixed ; re-open this ticket if the issue is still there.
