### ISSUE TITLE
Add Antwerp, Belgium

### ISSUE THREAD

**Issue by stijnhuy** [EqualStreetNames/equalstreetnames#412]
Hi, i started adding name:etymology:wikidata tags in OSM for Antwerp a couple of weeks ago.
I made a repository: https://github.com/stijnhuy/equalstreetnames-antwerp
Can this be added to this cool project?

**Comment by jbelien** [comment]
Nice, welcome @stijnhuy !

You should have received an invite to join @EqualStreetNames/antwerp 
Once you've joined, you'll be able to transfer your repository to @EqualStreetNames and I'll take care of the last steps.

**Comment by jbelien** [comment]
Don't forget to add `MAPBOX_TOKEN` in your [repository secrets](https://github.com/EqualStreetNames/equalstreetnames/settings/secrets/actions) (see https://github.com/EqualStreetNames/equalstreetnames-template#integrate-your-city-to-the-project).

⚠️ For consistency with the other cities in Belgium, I renamed your repository to [`EqualStreetNames/equalstreetnames-antwerpen`](https://github.com/EqualStreetNames/equalstreetnames-antwerpen)

**Comment by jbelien** [comment]
🚀 Deployed: https://antwerpen.equalstreetnames.be/

2 remarks:
- Separator in `data.csv` was incorrect (`;` instead of `,`)
- `MAPBOX_TOKEN` is not a valid Mapbox token (see https://docs.mapbox.com/help/getting-started/access-tokens/), please update it
