### ISSUE TITLE
Streets in a OSM-Relation are not displayed

### ISSUE THREAD

**Issue by CaptainInler** [EqualStreetNames/equalstreetnames#427]
OSM-Street's that are member of a Relation wont get rendered in the Map.

Example:
Wyssgasse 
- https://www.openstreetmap.org/way/5944788
- https://zurich.equalstreetnames.eu/de/index.html#18.41/47.373802/8.525517

Stauffacherstrasse
- https://www.openstreetmap.org/way/11917566
- https://zurich.equalstreetnames.eu/de/index.html#18.1/47.378372/8.520375
-> The northwestern Part of this street is not in a Relation and gets rendered on the map

**Comment by jbelien** [comment]
Strange, for Brussels most of the streets are also relations with `type=associatedStreet` and it works just fine.
I'll need to investigate.

Can you check that your Overpass queries extract correctly those streets ?

**Comment by CaptainInler** [comment]
The Overpass query works. But somehow most of the geometries in relations.geojson do not have there wikidata tag anymore. There is also [Hallwylstrasse](https://www.openstreetmap.org/relation/2956736) in Bern with the same issue.
I tried to figure out how to run your processing toolchain, but I didn't succeed.

**Comment by jbelien** [comment]
Thanks for your feedback @CaptainInler !

I'll have a look when I have some free time.

**Comment by metaodi** [comment]
I'm not sure if this helps: but I checked the [relation of Wyssgasse](https://www.openstreetmap.org/way/5944788) and added the `name:etymology:wikidata` attribute directly on the relation (rather than on the way *in* the relation) and this seems to do the trick. At least looking at the [map](https://zurich.equalstreetnames.eu/de/index.html#18.41/47.373802/8.525517) now, Wyssgasse is rendered.

**Comment by jbelien** [comment]
Nice, thanks for the update @metaodi 👍 

@CaptainInler Could you check again and let me know if this is still an issue ? Thanks.

**Comment by CaptainInler** [comment]
@jbelien Yes this did the trick.
