### ISSUE TITLE
Kaiserslautern (Germany) is ready

### ISSUE THREAD

**Issue by BerenikeRe** [EqualStreetNames/equalstreetnames#455]
Hello everyone!
I just finished updating & uploading everything for the streets of Kaiserslautern, Germany. You can look at it here: https://github.com/BerenikeRe/equalstreetnames-kaiserslautern
I would like to transfer the repository to the EqualStreetNames organization.
Best wishes from Mainz
Berenike

**Comment by jbelien** [comment]
Thanks @BerenikeRe !
I'll set up the team so you can transfer the repository ASAP ; stay tuned 😄

**Comment by jbelien** [comment]
Done: @EqualStreetNames/kaiserslautern 
You can now transfer the repository.

**Comment by BerenikeRe** [comment]
I think (and hope) I transfered it the right way :)

**Comment by jbelien** [comment]
You did 👍 
I'll take care of the next steps.

Could you already add a valid Mapbox token in the [repository secrets](https://github.com/EqualStreetNames/equalstreetnames-kaiserslautern/settings/secrets/actions) (see [documentation](https://github.com/EqualStreetNames/equalstreetnames-template#integrate-your-city-to-the-project)) ?

**Comment by jbelien** [comment]
Everything is ready, we just need the Mapbox token to display the map and once it's done I'll be able to finish the setup to publish the website.

**Comment by BerenikeRe** [comment]
Thank you Jonathan! I added the Mapbox token.

**Comment by jbelien** [comment]
🚀 And it's now deployed: https://kaiserslautern.equalstreetnames.eu/en/index.html

Welcome on board! Keep on the good work!
