### ISSUE TITLE
documentation: slight confusion Brussels vs Bruges

### ISSUE THREAD

**Issue by 62mkv** [EqualStreetNames/equalstreetnames#492]
Hi 

Just wanted to point out that "Q12994" is not Brussels: it's Bruges :) it's mentioned as Brussels though throughout the template README

**Comment by jbelien** [comment]
You're absolutely right.
Thanks for the notice.
It has been updated in https://github.com/EqualStreetNames/equalstreetnames-template/commit/4992874ef3cc3b7c1008ea9aba8d8644cfcf48f6
