### ISSUE TITLE
Ready to add a new city to the project - Rixensart

### ISSUE THREAD

**Issue by vdarmsta** [EqualStreetNames/equalstreetnames#519]
Hi,

I have replicated the EqualStreetNames project in my city, Rixensart in Wallonia, following the instruction in the README.md file.

I now would like to add it as new city to the project.

I think best would be that I keep the ownership of my repository.

My repository is here: https://github.com/vdarmsta/EqualStreetNames-Rixensart

Let me know if all is in order or if anything is missing.

Thanks in advance,

Vincent

**Comment by jbelien** [comment]
Awesome!
You should have received an invitation to join @EqualStreetNames/rixensart team.
Once you've joined you should be able to transfer your repository to @EqualStreetNames organization and I'll take care of the next steps.

**Comment by jbelien** [comment]
Don't forget to add the `MAPBOX_TOKEN` secret !

**Comment by vdarmsta** [comment]
> Don't forget to add the `MAPBOX_TOKEN` secret !

Hi Jonathan, I thought I already replied to you, but not sure it was sent or not.
Anyway, could you help me about how to create the MapBox_Token and also, where to add it? I haven't found that info in the README. What I have found is the link to the Mapbox doc. I followed it and I'm ready to create a token, but not sure what I have to select for the Token Scope and if I can add something in the token restriction (URL) or not (if yes, which URL can I put)?
Thanks in advance and sorry for the delay in my reaction.

**Comment by jbelien** [comment]
> [...] but not sure what I have to select for the Token Scope [...]

You can select everything.

![image](https://user-images.githubusercontent.com/1150563/165456404-a1060b67-61d6-4cee-baef-33239ffefe41.png)

> [...] and if I can add something in the token restriction (URL) or not (if yes, which URL can I put)?

You can put `https://rixensart.equalstreetnames.be` in the list of URLs.

> Anyway, could you help me about how to create the MapBox_Token and also, where to add it?

Once you have your token, you need to create a `MAPBOX_TOKEN` in your repository secrets.
https://github.com/EqualStreetNames/equalstreetnames-rixensart/settings/secrets/actions (in "Repository secrets")

**Comment by vdarmsta** [comment]
Hi,

Ok, this is done.

Let me know if this works and if there is still something to do on my side.

Best regards,

Vincent

**Comment by jbelien** [comment]
Data update and deployment are on their way!
I'll take care of the DNS settings this weekend. 😃

**Comment by jbelien** [comment]
🚀 Deployed: https://rixensart.equalstreetnames.be/
