### ISSUE TITLE
Add Basel, Switzerland

### ISSUE THREAD

**Issue by CaptainInler** [EqualStreetNames/equalstreetnames#520]
Hi. Please add Basel to the Project.
The repo to copy is here: https://github.com/CaptainInler/equalstreetnames-basel

**Comment by jbelien** [comment]
Hello @CaptainInler , you should have received an invite to join @EqualStreetNames/basel !

Once joined, you should be able to transfer your repository to @EqualStreetNames organization and I'll take care of the next steps.

**Comment by CaptainInler** [comment]
Hi @jbelien. The Repo is transfered. Thanks for your work.

**Comment by jbelien** [comment]
@CaptainInler Don't forget to add the `MAPBOX_TOKEN` secret!

**Comment by CaptainInler** [comment]
Mapbox_Token is added

**Comment by jbelien** [comment]
Deployed: https://basel.equalstreetnames.eu/ 🚀

**Comment by CaptainInler** [comment]
Cool. @jbelien Thank you so much 🙌
