### ISSUE TITLE
Please add estonia-tartu project

### ISSUE THREAD

**Issue by 62mkv** [EqualStreetNames/equalstreetnames#585]
https://github.com/62mkv/equalstreetnames-tartu

**Comment by jbelien** [comment]
Awesome! 👍 

You should have received an invite to join @EqualStreetNames/tartu ;
You can transfer your repository to @EqualStreetNames

**Comment by jbelien** [comment]
Hello @62mkv ,

The repository is indeed correctly transfered! ✔️

The `MAPBOX_TOKEN` secret is missing and it's indeed required ; you can use the same token you used for Tallinn, you will just have to add it to Tartu repository [settings](https://github.com/EqualStreetNames/equalstreetnames-tartu/settings/secrets/actions).

⚠ If you used "Token restrictions" for the Tallinn token and you use the same token Tartu, you will also have to add `https://tartu.equalstreetnames.eu/` in the list of allowed URLs.

**Comment by jbelien** [comment]
> for some reason, the link above (https://github.com/EqualStreetNames/equalstreetnames-tartu/settings/secrets/actions) is 404 for me :( And I don't see "Settings" in the repository menu anymore.

You're right! I've fixed it, you now have access to the settings.

> would it be possible to ask to set same `MAPBOX_TOKEN` that is used for Tallinn repo, to be used for Tartu repo as well?

It's definitely not a problem to use the same token for both.
But you will have to do it yourself ; you're the only one to know the value of that token.

**Comment by 62mkv** [comment]
Ok, I see now; nobody can see the token value on GH; only update or remove.

I've added my MB token for the "tartu" repository as well, let's see how it goes!

**Comment by jbelien** [comment]
Thanks!
I'll take care of the next steps later this week.

**Comment by jbelien** [comment]
Deployed: https://tartu.equalstreetnames.eu/ 🚀
