### ISSUE TITLE
Centralized statistics page

### ISSUE THREAD

**Issue by 62mkv** [EqualStreetNames/equalstreetnames#586]
Hi, I would love to be able to see some aggregated stats across all project cities, that would display latest data collected for project, such as: 
- basic OSM stats (X ways, Y relations processed) 
- basic WikiData stats (Z items retrieved, K named after persons, .. of each gender)

For example, based on 2 Estonian cities I did, and comparing them to some German ones, it's easy to notice that Estonian cities have WAY less street names named after persons in general (2-3% for Estonian cities vs 30% for Berlin), and dismal share of women in that selection (2-5% vs 11-15% for German cities). It would be cool to be able to spot such artifacts right away on the same page. 

not sure as to where exactly would that sit, maybe update and commit some page in this project from the CI, and link that page from the README?

**Comment by jbelien** [comment]
@RobinLinde has created https://statistics.equalstreetnames.eu/ where you can find some statistics.

**Comment by 62mkv** [comment]
This page still does not have Tartu, btw :)
