### ISSUE TITLE
Add Tivat, Montenegro

### ISSUE THREAD

**Issue by 62mkv** [EqualStreetNames/equalstreetnames#615]
https://github.com/62mkv/equalstreetnames-tivat

Maybe not the best example, really not too many streets named after people, but I have lived there for some time so that was my hommage :) 

PS: at least 4 streets are named after people, information on whom is genuinely impossible to find remotely 😱

**Comment by 62mkv** [comment]
again (as with Tartu) I have no access to Settings in transferred repository

**Comment by jbelien** [comment]
> again (as with Tartu) I have no access to Settings in transferred repository

You loose those access when you transfer your repository.
I've created the @EqualStreetNames/tivat team and you know have admin rights again.

I'll take care of the next steps in the next few days.

**Comment by jbelien** [comment]
🚀 Deployed on https://tivat.equalstreetnames.eu/

**Comment by 62mkv** [comment]
Is it supposed to by ".MyCity" ? 

![image](https://user-images.githubusercontent.com/5255127/189120594-3572cb57-83eb-483c-b850-576b4dc8104d.png)

**Comment by jbelien** [comment]
> Is it supposed to by ".MyCity" ?

That's fully under your control.
See here (or [documentation](https://github.com/EqualStreetNames/equalstreetnames-template#readme)):
- https://github.com/EqualStreetNames/equalstreetnames-tivat/blob/master/html/index.html#L9
- https://github.com/EqualStreetNames/equalstreetnames-tivat/blob/master/html/en/index.html#L11
- https://github.com/EqualStreetNames/equalstreetnames-tivat/blob/master/html/en/index.html#L23

**Comment by 62mkv** [comment]
Thanks @jbelien, I must have forgotten about that!
