### ISSUE TITLE
Wish to start EqualStreetNames.CapeTown

### ISSUE THREAD

**Issue by Rodeobe** [EqualStreetNames/equalstreetnames#635]
Available here: https://github.com/Rodeobe/CapeTownEqualStreetNames

How can I get this transfered to you, the "EqualStreetNames organization"? Thx

**Comment by jbelien** [comment]
Hello @Rodeobe,
Welcome to the project!

You should have received an invite to join @EqualStreetNames/cape-town 
As soon as you accept that invite, you should be able to transfer your repository to @EqualStreetNames organization.

Once transferred, I'll take care of the next steps.

**Comment by jbelien** [comment]
I have started the work in PR #643 but the `MAPBOX_TOKEN` is missing in the [repository secrets](https://github.com/EqualStreetNames/equalstreetnames-capetown/settings/secrets/actions).

Please add it so I can finish the integration (see [documentation](https://github.com/EqualStreetNames/equalstreetnames-template#integrate-your-city-to-the-project) if needed).
